export const vouchers = [
  {
    brand: 'Amazon',
    image: require('../assets/Logos/Amazon.png'),
    coins: 1500,
    giftCard: 5000,
    status: 'UNLOCKED',
    backgroundColors: ['#4D2C9D', '#442D83'],
    coinBackground: '#190748',
  },
  {
    brand: 'Beardo',
    image: require('../assets/Logos/Beardo.png'),
    coins: 1500,
    giftCard: 5000,
    status: 'UNLOCKED',
    backgroundColors: ['#D8636E', '#871A44'],
    coinBackground: '#48091D',
  },
  {
    brand: 'Hotstar',
    image: require('../assets/Logos/Hotstar.png'),
    coins: 1500,
    giftCard: 5000,
    status: 'UNLOCKED',
    backgroundColors: ['#AD7034', '#E1AC76'],
    coinBackground: '#723800',
  },
  {
    brand: 'Flipkart',
    image: require('../assets/Logos/Flipkart.png'),
    coins: 1500,
    giftCard: 5000,
    status: 'LOCKED',
    backgroundColors: ['#4D2C9D', '#442D83'],
  },
  {
    brand: 'Nykaa',
    image: require('../assets/Logos/Nykaa.png'),
    coins: 1500,
    giftCard: 5000,
    status: 'LOCKED',
    backgroundColors: ['#4D2C9D', '#442D83'],
  },
  {
    brand: 'Mamaearth',
    image: require('../assets/Logos/Mamaearth.png'),
    coins: 1500,
    giftCard: 5000,
    status: 'LOCKED',
    backgroundColors: ['#4D2C9D', '#442D83'],
  },
  {
    brand: 'Boat',
    image: require('../assets/Logos/Boat.png'),
    coins: 1500,
    giftCard: 5000,
    status: 'LOCKED',
    backgroundColors: ['#4D2C9D', '#442D83'],
  },
  {
    brand: 'Oneplus',
    image: require('../assets/Logos/Oneplus.png'),
    coins: 1500,
    giftCard: 5000,
    status: 'LOCKED',
    backgroundColors: ['#4D2C9D', '#442D83'],
  },
];
